### PR TITLE
Remove @emotion/styled usage

### LINKED ISSUE #1183: Typescript forwarding ref issue
Hey, 

If i use Box and then i apply ref forwarding on a new component called button. It would seem that in typescript when using forward ref it seems that box is set to HTMLDivElement and if i supply HTMLButtonElement we get error that it needs to be a div element, i assume this is to do with the 'as' prop?

Just wandered what i'm doing wrong - i even tried the typings for ForwardRef and it still did not work. TS version 4.0.2

for example:
```Javascript
import * as React from 'react';
import { Box, BoxProps } from 'my-lib';

export interface IButtonProps extends BoxProps {
  label: string;
  variant?: 'primary' | 'secondary' | 'tertiary';
  children: React.ReactNode;
}

const Button = React.forwardRef<
  HTMLButtonElement,
  IButtonProps,
>(({ label = 'change me', variant = 'primary', ...rest }, ref) => {
  return (
    <Box
      as="button"
      ref={ref}
      variant={variant}
      aria-label={label}
      {...rest}
    />
  );
});

export { Button };
```

```
Type '((instance: HTMLButtonElement | null) => void) | MutableRefObject<HTMLButtonElement | null> | null' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
  Type '(instance: HTMLButtonElement | null) => void' is not assignable to type 'string | ((instance: HTMLDivElement | null) => void) | RefObject<HTMLDivElement> | null | undefined'.
    Type '(instance: HTMLButtonElement | null) => void' is not assignable to type '(instance: HTMLDivElement | null) => void'.
      Types of parameters 'instance' and 'instance' are incompatible.
        Type 'HTMLDivElement | null' is not assignable to type 'HTMLButtonElement | null'.
          Type 'HTMLDivElement' is missing the following properties from type 'HTMLButtonElement': disabled, form, formAction, formEnctype, and 13 more.ts(2322)
index.d.ts(143, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & Pick<...> 
```

Thanks in advance ;-)

### LINKED ISSUE #1417: Remove @emotion/styled from mdx package
To correspond with #1368, let's remove @emotion/styled from the mdx package so it's no longer an internal dependency of Theme UI. This should cut bundle size noticeably.

Related: #1183

### LINKED ISSUE #1420: Duplicate package @emotion/is-prop-valid through styled-system dependency
**Describe the bug**

When using `DuplicatePackageCheckerPlugin` with the latest version `0.6.0-alpha.4` and `"@emotion/react": "^11.1.4"` and `"@emotion/styled": "^11.0.0"` I'm seeing:

```
warn  - @emotion/is-prop-valid
  Multiple versions of @emotion/is-prop-valid found:
    0.8.8 ./~/@emotion/is-prop-valid
    1.0.0 ./~/@emotion/styled/~/@emotion/is-prop-valid
```

**To Reproduce**

Add https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin to the project using Theme UI and try building.

**Expected behavior**

No duplicated packages should be added to the bundle.

**Additional context**

```
➜ npx npm-why @emotion/is-prop-valid

  Who required @emotion/is-prop-valid:

  monolisa-website > theme-ui > @theme-ui/components > @styled-system/should-forward-prop > @emotion/is-prop-valid@0.8.8
```

so it looks like it's coming from styled-system which is a dependency of Theme UI and probably needs to be updated there.

### PR DESCRIPTION
**Pull request by hasparus**
Continues work of old PR https://github.com/system-ui/theme-ui/pull/1368.

<details>
  <summary>📦 Published PR as canary version: <code>0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @theme-ui/color-modes@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/color@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/components@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/core@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/css@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/custom-properties@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/editor@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install gatsby-plugin-theme-ui@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install gatsby-theme-style-guide@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install gatsby-theme-ui-layout@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/match-media@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/mdx@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/parse-props@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-base@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-bootstrap@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-bulma@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-dark@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-deep@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-funk@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-future@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-polaris@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-roboto@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-sketchy@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-swiss@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-system@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-tailwind@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/preset-tosh@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/presets@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/prism@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/sidenav@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/style-guide@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/tailwind@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/theme-provider@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install theme-ui@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  npm install @theme-ui/typography@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  # or 
  yarn add @theme-ui/color-modes@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/color@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/components@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/core@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/css@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/custom-properties@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/editor@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add gatsby-plugin-theme-ui@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add gatsby-theme-style-guide@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add gatsby-theme-ui-layout@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/match-media@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/mdx@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/parse-props@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-base@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-bootstrap@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-bulma@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-dark@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-deep@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-funk@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-future@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-polaris@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-roboto@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-sketchy@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-swiss@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-system@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-tailwind@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/preset-tosh@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/presets@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/prism@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/sidenav@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/style-guide@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/tailwind@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/theme-provider@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add theme-ui@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  yarn add @theme-ui/typography@0.14.0--canary.2043.a8ab69e57240f26f57b17517635946d6918bb5e7.0
  ```
</details>

### CODE REVIEW

File: packages/components/src/Box.tsx [hunk 1]
```diff
@@ -0,0 +1,168 @@
...
+  return <Component ref={ref} css={style} {...rest} />
+})
+
+/**
+ * Use the Box component as a layout primitive to add margin, padding, and colors to content.
+ * @see https://theme-ui.com/components/box
+ */
+export const Box = __Box as typeof __Box & {
+  /**
+   * @deprecated
```
Comment (lachlanjc) [inline packages/components/src/Box.tsx]: This has been deprecated for more releases than we said it would be available, I'm fine removing it

File: packages/components/src/Close.tsx [hunk 2]
```diff
@@ -0,0 +1,40 @@
+import React from 'react'
+
+import { IconButton, IconButtonProps } from './IconButton'
+import type { ForwardRef } from './types'
+
+const X_ICON = (
```
Comment (lachlanjc) [inline packages/components/src/Close.tsx]: It's nbd, but this isn't stylistically consistent with `CheckboxChecked`

File: packages/components/src/Embed.tsx [hunk 3]
```diff
@@ -0,0 +1,80 @@
+// @ts-check
```
Comment (lachlanjc) [inline packages/components/src/Embed.tsx]:
```suggestion
```
Shouldn't be necessary?

File: packages/components/src/Flex.tsx [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+
+/**
+ * Use the Flex component to create flexbox layouts.
+ * @see https://theme-ui.com/components/flex
+ */
+export const Flex = __Flex as typeof __Flex & {
+  /**
+   * @deprecated
+   */
+  withComponent: (Component: React.ElementType) => React.ComponentType<BoxProps>
```
Comment (lachlanjc) [inline packages/components/src/Flex.tsx]: Not clear why Flex needs this but not other components like Grid if Box implements it? Regardless, I'm happy with removing here as well

File: packages/components/src/IconButton.tsx [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+      <Box
+        ref={ref}
+        as="button"
+        variant="icon"
+        {...props}
+        // @ts-expect-error
+        __themeKey="buttons"
+        __css={{
+          // @ts-expect-error
+          label: props.__css?.label || 'IconButton',
```
Comment (lachlanjc) [inline packages/components/src/IconButton.tsx]: Can we add a code comment with what this is doing?

File: packages/components/src/MenuButton.tsx [hunk 6]
```diff
@@ -0,0 +1,41 @@
+/** @jsx jsx */
+import { jsx } from '@emotion/react'
+import React from 'react'
+
+import { IconButton, IconButtonProps } from './IconButton'
+import type { ForwardRef } from './types'
+
+export const MenuIcon = ({ size = 24 }) => {
```
Comment (lachlanjc) [inline packages/components/src/MenuButton.tsx:8]: We should either export all our internal icons (Checkbox & Close & Radio) or document why. I think the Checkboxes are less useful outside the library but Close should be exported if this is

**Review by lachlanjc — COMMENTED** [review]
Omg, thank you thank you for this massive upgrade!! Such an improvement. I've reviewed the diff for the first 2/3 & will get to the rest later, but this seems like the perfect implementation.

File: packages/components/src/Progress.tsx [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+import { ThemeUICSSObject } from '@theme-ui/css'
+
+import { Box, BoxOwnProps } from './Box'
+import type { Assign, ForwardRef } from './types'
+
+export interface ProgressProps
+  extends Assign<React.ComponentPropsWithRef<'progress'>, BoxOwnProps> {}
+
+/**
+ * @see https://theme-ui.com/components/progress/
```
Comment (lachlanjc) [inline packages/components/src/Progress.tsx:14]: Ideally would add the text description here?

File: packages/components/src/Progress.tsx [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+    }
+
+    return (
+      <Box
+        ref={ref}
+        as="progress"
+        variant="styles.progress"
+        {...props}
+        // @ts-expect-error internal prop
+        __css={}
```
Comment (lachlanjc) [inline packages/components/src/Progress.tsx]:
```suggestion
        __css={__css}
```
Seems like this isn't hooked up

File: packages/components/src/Embed.tsx (hunk 3 above)
Comment (hasparus) [reply packages/components/src/Embed.tsx]: Oh, yeah, I missed it.

File: packages/components/src/SVG.tsx [hunk 9]
```diff
@@ -0,0 +1,24 @@
...
+
+import { Box, BoxOwnProps } from './Box'
+import type { Assign } from './types'
+
+export interface SVGProps
+  extends Assign<SVGAttributes<SVGElement>, BoxOwnProps> {
+  size?: number | string
+}
+
+export const SVG = ({ size = 24, ...rest }: SVGProps) => {
```
Comment (lachlanjc) [inline packages/components/src/SVG.tsx:11]: Missing comment with link to docs. Update: appears we have no docs for this component.

File: packages/components/src/Select.tsx [hunk 10]
```diff
@@ -0,0 +1,67 @@
...
+  React.forwardRef(function Select({ arrow, ...props }, ref) {
+    const __css: ThemeUICSSObject = {
+      display: 'block',
+      width: '100%',
+      p: 2,
+      appearance: 'none',
+      fontSize: 'inherit',
+      lineHeight: 'inherit',
+      border: '1px solid',
+      borderRadius: 4,
```
Comment (lachlanjc) [inline packages/components/src/Select.tsx:36]: For styles like this, should we use `theme.radii?.[1] || 4`?

File: packages/components/src/Switch.tsx [hunk 11]
```diff
@@ -0,0 +1,93 @@
...
+        cursor: 'not-allowed',
+      },
+      '& > div': {
+        display: 'flex',
+        alignItems: 'center',
+        borderRadius: '50%',
+        height: SIZE,
+        width: SIZE,
+        bg: 'white',
+        boxShadow: '0 1px 2px rgba(0, 0, 0, 0.1)',
```
Comment (lachlanjc) [inline packages/components/src/Switch.tsx:48]: Similarly to my radii comment

File: packages/components/test/Buttons.spec.tsx [hunk 12]
```diff
@@ -0,0 +1,30 @@
...
+
+import React from 'react'
+import { renderJSON } from '@theme-ui/test-utils'
+import { ThemeProvider } from 'theme-ui'
+
+import { Button } from '..'
+
+import { theme } from './__test-utils__'
+
+describe('Button', () => {
```
Comment (lachlanjc) [inline packages/components/test/Buttons.spec.tsx]: Since this describes `Button`, name the file `Button` instead of `Buttons` for consistency?

**Review by lachlanjc — COMMENTED** [review]
Finished reading the diff, this is all looking great! Seems like the last piece is adding very basic tests for the other components, & updating docs about migrating to the peer dep. But so appreciate you taking this on.

**Comment by lachlanjc** [comment]
Do you think this fixes all the context mismatch issues??

**Comment by lachlanjc** [comment]
Ah, & https://github.com/system-ui/theme-ui/pull/1368#issuecomment-746958397 is still relevant. Seems like we could 1) deprecate Themed now, planning to remove it when all this launches 2) move it to a separate package that still depends on /styled, or 3) re-implement it without /styled. What are you in favor of?

File: packages/components/src/Progress.tsx (hunk 7 above)
Comment (hasparus) [reply packages/components/src/Progress.tsx:14]: Dude, I can't believe you reviewed this the same day as I pushed :D

Comment (hasparus) [reply packages/components/src/Progress.tsx:14]: How about this:

```suggestion
 * Horizontal `<progress />` bar
 * @see https://theme-ui.com/components/progress/
```

BTW, I noticed the docs are a bit silly here :D

image

File: packages/components/src/Progress.tsx (hunk 8 above)
Comment (hasparus) [reply packages/components/src/Progress.tsx]: Oh, yeah. Definitely. Dangers of `@ts-expect-error`.

**Comment by hasparus** [comment]
> Do you think this fixes all the context mismatch issues??

@lachlanjc Well, it depends on https://github.com/system-ui/theme-ui/pull/1867, so it should help with it. I mean, the user will still be able to install multiple Emotion versions through other deps thus breaking all of their stuff depending on Emotion (including us) but we'll at least avoid adding to the problem.

File: packages/components/src/MenuButton.tsx (hunk 6 above)
Comment (hasparus) [reply packages/components/src/MenuButton.tsx:8]: Fair point.

File: packages/components/src/Progress.tsx (hunk 7 above)
Comment (lachlanjc) [reply packages/components/src/Progress.tsx:14]: Lol yeah, need to take a pass through those. Noted!

File: packages/components/src/SVG.tsx (hunk 9 above)
Comment (lachlanjc) [reply packages/components/src/SVG.tsx:11]: Didn’t realize we don’t export this component publicly! Resolving.

File: packages/components/src/Select.tsx (hunk 10 above)
Comment (lachlanjc) [reply packages/components/src/Select.tsx:36]: This is a feature for another branch/time, resolving.

File: packages/components/src/MenuButton.tsx (hunk 6 above)
Comment (lachlanjc) [reply packages/components/src/MenuButton.tsx:8]: Fixed this by exporting `CloseIcon`!

File: packages/components/src/Progress.tsx (hunk 7 above)
Comment (lachlanjc) [reply packages/components/src/Progress.tsx:14]: Fixed that separately in #2069.

File: packages/components/src/IconButton.tsx (hunk 5 above)
Comment (lachlanjc) [reply packages/components/src/IconButton.tsx]: This still stands out as a bit confusing to me

**Comment by lachlanjc** [comment]
This is looking exciting!! Is there any more work you're looking to do here before we merge?

Edit: after I fixed a minor merge conflict in 2 package.json files, CI is failing a bunch of tests now…sigh

**Comment by lachlanjc** [comment]
@hasparus I’ve continued fixing merge conflicts & making small updates to this branch, but the core issue is that the components it’s rendering (even from before fixing the merge conflicts) aren’t styled—if you click one of the early View Deployment buttons in the thread, components like buttons aren’t rendering their sx props: https://theme-ui-pd8th9yw1-systemui.vercel.app/. I haven’t dug super deeply into that issue yet, is this already on your radar or one of us needs to get to the bottom of it?

**Comment by hasparus** [comment]
@lachlanjc I fixed a few leftover bugs in `@theme-ui/mdx`.

`scripts/typecheck-built-files` really needs a migration to PNPM it seems.

File: packages/components/src/IconButton.tsx (hunk 5 above)
Comment (hasparus) [reply packages/components/src/IconButton.tsx]: Nice catch. I preserved it because it was there already, but it seems that no other component passes [Emotion label](https://emotion.sh/docs/labels) to `IconButton`.

File: MIGRATING.md [hunk 13]
```diff
@@ -1,5 +1,14 @@
 # Migration Guides
 
+## v0.14
+
+- `@theme-ui/components` and other Theme UI packagss no longe depends on
```
Comment (lachlanjc) [inline MIGRATING.md]:
```suggestion
- `@theme-ui/components` and other Theme UI packages no longer depend on
```

File: packages/components/src/Close.tsx [hunk 14]
```diff
@@ -0,0 +1,41 @@
...
+
+import { IconButton, IconButtonProps } from './IconButton'
+import type { ForwardRef } from './types'
+
+export const CloseIcon = (
+  <svg
+    xmlns="http://www.w3.org/2000/svg"
+    width="24"
+    height="24"
+    fill="currentolor"
```
Comment (lachlanjc) [inline packages/components/src/Close.tsx]:
```suggestion
    fill="currentColor"
```

File: MIGRATING.md (hunk 13 above)
Comment (hasparus) [reply MIGRATING.md]: Oh god, I made so many mistakes in that sentence xD

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:
