### PR TITLE
Use media query value when useColorSchemeMediaQuery is set to 'system'

### LINKED ISSUE #787: Unexpected `prefers-color-scheme` behaviour
**Describe the bug**

When toggling between light/dark mode on a supoprted device (in this case iOS, or MacOS via Firefox), Theme-UI's color scheme does not update. Updating the app to reflect the user's color mode requires the localstorage to be deleted.

> but may I add, setting up dark/light mode in it's current state has been an absolute breeze - thank you!

**To Reproduce**
1. Follow steps outlined in https://theme-ui.com/color-modes/
2. Clear local storage and refresh
3. App should render with your system preferences
4. Try toggling between light/dark mode in your system preferences and watch the behaviour of the app.

**Expected behavior**

As I've enabled `useColorSchemeMediaQuery`, I would expect the color modes to behave as a media query (in other words, on user-agent change - much like a breakpoint).

**Screenshots**

*An example in Theme-UI: (using `useColorSchemeMediaQuery`)*

Demo site toggling between dark and light mode on an iPhone

*Examples of 'expected behaviour' in non-Theme-UI applications* 

Twitter toggling dark and light mode

DuckDuckGo

**Additional context**
Related issues: https://github.com/system-ui/theme-ui/issues/367

### PR DESCRIPTION
**Pull request by draekien**
This PR is based on the changes proposed in https://github.com/system-ui/theme-ui/pull/981 and fixes https://github.com/system-ui/theme-ui/issues/787

This change adds a new option for `useColorSchemeMediaQuery` called `'system'` which will
listen for changes to the `prefers-color-scheme` media query and update the color mode
accordingly.

This change also updates the documentation to include a short description for the `'system'` option.

I decided to go with `'system'` over `'live'` as I've mostly encountered websites referring to the
user's preferred color scheme as the 'system' setting. Let me know if you would prefer `'live'` instead.

Testing: `'system'`
color-scheme-change

Testing: `'initial'` | `true`
color-scheme-initial

### CODE REVIEW

**Comment by lachlanjc** [comment]
Wow, phenomenal work!! Haven't tested it out but looks great. Super appreciate the contribution.

**Comment by draekien** [comment]
> Wow, phenomenal work!! Haven't tested it out but looks great. Super appreciate the contribution.

Thanks! I'm loving the library so wanted to see if I could contribute. Keep up the great work!!

File: packages/css/src/options.ts [hunk 1]
```diff
@@ -25,7 +25,7 @@ export interface ThemeUIConfig {
   /**
    * Initializes the color mode based on the prefers-color-scheme media query
    */
-  useColorSchemeMediaQuery?: boolean
+  useColorSchemeMediaQuery?: 'system' | 'initial' | boolean
```
Comment (hasparus) [inline packages/css/src/options.ts]:
```suggestion
  useColorSchemeMediaQuery?: 'system' | 'initial' | true /* same as 'initial' for compat */ | false
```

We can later update the docs to refer to `"initial"` instead of `true`.

**Comment by hasparus** [comment]
Great PR @draekien! Thank you for the contribution!

**Review by lachlanjc — APPROVED** [review]
Tried this locally & works exactly as I'd expect!

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.12.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.12.0) :rocket:
