### PR TITLE
fix: Unsupported Prism Languages

### LINKED ISSUE #160: Unsupported Prism Languages
`@theme-ui/prism` uses [`prism-react-renderer`](https://github.com/FormidableLabs/prism-react-renderer), [which does not include all languages supported by Prism](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) by default. So if you use one of the missing languages, it simply does not highlight:

```r
# r language
# no syntax highlighting on theme-ui
```

A fix would be to pass `Prism` as a prop on `Highlight` component, [as documented here](https://github.com/FormidableLabs/prism-react-renderer#prism). I think the best approach would be to allow passing `Prism` to [`index.js`](https://github.com/system-ui/theme-ui/blob/master/packages/prism/src/index.js#L7) like this:

```jsx
export default ({ children, className, title, Prism }) => {
  // ...
  
  return (
    <Highlight
	  {...defaultProps}	
      Prism={Prism || defaultProps.Prism}
      ... />
  )
}
```

So that it could be customized like:

```jsx
import CodeBlock from '@theme-ui/prism'
import Prism from 'prismjs/components/prism-core'
import 'prismjs/components/prism-r'

<CodeBlock Prism={Prism} ... />
```

### PR DESCRIPTION
**Pull request by johnletey**
@jxnblk I believe that I have fixed the issue that @chibicode reported! Let me know if there is anything else I need to do 😄

Closes #160

### CODE REVIEW

File: packages/prism/src/index.js [hunk 1]
```diff
@@ -4,12 +4,15 @@
...
-export default ({ children, className: outerClassName, title }) => {
+import Prism from 'prismjs/components/prism-core'
+
+export default ({ children, className: outerClassName, title, prism }) => {
   const [language] = outerClassName.replace(/language-/, '').split(' ')
 
   return (
     <Highlight
       {...defaultProps}
+      Prism={Prism || prism}
```
Comment (jxnblk) [inline packages/prism/src/index.js]: Thanks for looking into this! This *looks like* it would always evaluate to the imported module, but I don't think that's the intent, is it?

Comment (johnletey) [reply packages/prism/src/index.js]: No @jxnblk ... the intention is to check to see if the user passed the function a ‘prism’ parameter, and if they didn’t, we’ll use the one that we imported

Comment (johno) [reply packages/prism/src/index.js]: Right, but I think @jxnblk's point is that it should be `{prism || Prism}` if I understand this correctly?

Comment (johno) [inline packages/prism/src/index.js]:
```suggestion
      Prism={prism || Prism}
```

Comment (johnletey) [reply packages/prism/src/index.js]: I think you are right @johno
