### PR TITLE
fix: Allow overriding Paragraph margins via theme

### LINKED ISSUE #1774: Paragraph margin can't be overridden by theme
**Describe the bug**
Paragraph margins can't be changed via theming because the `m={0}` value is always added after applying the theme. This was first fixed in #1476, but reintroduced by #1560.

**To Reproduce**
I created a sandbox in https://codesandbox.io/s/aged-silence-42b7m
See the output - all 4 paragraphs should have margins applied.

**Expected behavior**
Margins should be set to 0 by default. But no matter what method of styling you prefer, they should always be overrideable. 

**Screenshots**
image

**Additional context**
It seems that margin:0 is set twice. Maybe it helps to remove the `m={0}` completely because it's set anyway.
image

### PR DESCRIPTION
**Pull request by bernharduw**
This fixes #1774 - I found that margin: 0 is set by default (coming from Box maybe? Not 100% sure).

So if we don't set the margin for Paragraph manually, the specificity issues disappear.

I also added two tests using a theme override - the other two cases are already covered by the existing tests.

# Version

Published prerelease version: `v0.9.1-develop.0`

<details>
  <summary>Changelog</summary>

  #### 🐛 Bug Fix
  
  - `@theme-ui/components`
    - fix: Allow overriding Paragraph margins via theme [#1775](https://github.com/system-ui/theme-ui/pull/1775) ([@bernharduw](https://github.com/bernharduw))
  
  #### Authors: 1
  
  - Bernhard Gschwantner ([@bernharduw](https://github.com/bernharduw))
</details>

### CODE REVIEW

**Comment by hasparus** [comment]
Thanks for the PR @bernharduw!

**Comment by hasparus** [comment]
Doesn't this break the scenario when users depend on margin being set to 0 by default? (See snapshot in the diff.)

File: packages/components/test/__snapshots__/index.js.snap [hunk 1]
```diff
@@ -1097,7 +1097,6 @@ exports[`Paragraph renders 1`] = `
   font-family: body;
```
Comment (bernharduw) [inline packages/components/test/__snapshots__/index.js.snap:1097]: The snapshot still has `margin: 0` in it, but at the very beginning.

**Comment by bernharduw** [comment]
I think that way the effective margin on paragraphs is still 0, but can be overridden by any styling method, regardless of theme, styled-system-style or direct sx overrides. The tests still all pass, only the duplicate margin: 0 is reduced to a single occurrence.

The margin:0 in line 1095 comes from the Box which sets margin:0 as a default, so we should be safe here.

**Comment by hasparus** [comment]
Thanks! Yup, I can see that first `margin: 0`. Sorry!

**Review by hasparus — APPROVED** [review]

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.9.1-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.1-develop.0) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.9.1`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.1) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.9.2-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.2-develop.0) :rocket:

**Comment by sergeylukin** [comment]
WD for removing duplication. I, however, struggle to understand the purpose of Box's default margin: 0... which causes troubles when parent intends to set inner Boxes' margin via `'> * + *': 'marginLeft: 30px'` for instance.
Why do we need to set margin: 0? If it's inherited, we can set `m={0}` in case it's required (which is an edge case really).
Would love to know more about that. Thanks!
Hope that's not too far from the subject lol

**Comment by lachlanjc** [comment]
@sergeylukin I believe it's just a reset, since elements like form fields & lists often have margin applied by the default browser stylesheet. Happy to accept better solutions to that problem, though!
